/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dkkarthi' at '2/8/18 11:03 AM' with Gradle 2.14.1
 *
 * @author dkkarthi, @date 2/8/18 11:03 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
